name = "thank-you-survey"
uid = "36589f62-9892-39cb-2f34-f27a46d18b634b74a298"
type = "checkout_ui_extension"

[targeting]
target = "purchase.thank-you-page.render"

[settings]
[[settings.fields]]
key = "survey_title"
type = "single_line_text_field"
name = "Survey Title"

[[settings.fields]]
key = "survey_description"
type = "multi_line_text_field"
name = "Survey Description"

[[settings.fields]]
key = "questions"
type = "single_line_text_field"
name = "Survey Questions"
