name = "thank-you-survey"
type = "checkout_ui_extension"

[targeting]
target = "purchase.thank-you-page.render-after"

[settings]
[[settings.fields]]
key = "survey_title"
type = "single_line_text_field"
name = "Survey Title"
default = "How was your checkout experience?"

[[settings.fields]]
key = "survey_description"
type = "multi_line_text_field"
name = "Survey Description"
default = "Help us improve your shopping experience by sharing your feedback."

[[settings.fields]]
key = "questions"
type = "json"
name = "Survey Questions"
default = "[{\"id\":\"satisfaction\",\"type\":\"rating\",\"question\":\"How satisfied are you with your checkout experience?\",\"scale\":5},{\"id\":\"feedback\",\"type\":\"textarea\",\"question\":\"Any additional feedback?\",\"required\":false}]"
