name = "session-replay-pixel"
type = "web_pixel_extension"

[targeting]
target = "purchase.thank-you-page"
target = "purchase.order-status-page"

[settings]
[[settings.fields]]
key = "api_endpoint"
type = "single_line_text_field"
name = "API Endpoint"
default = "https://your-app-url.com/api/events"

[[settings.fields]]
key = "batch_size"
type = "number_integer_field"
name = "Event Batch Size"
default = 50

[[settings.fields]]
key = "batch_timeout"
type = "number_integer_field"
name = "Batch Timeout (ms)"
default = 5000

[[settings.fields]]
key = "enable_mouse_tracking"
type = "boolean_field"
name = "Enable Mouse Tracking"
default = true

[[settings.fields]]
key = "enable_scroll_tracking"
type = "boolean_field"
name = "Enable Scroll Tracking"
default = true

[[settings.fields]]
key = "enable_form_tracking"
type = "boolean_field"
name = "Enable Form Tracking"
default = true

[[settings.fields]]
key = "mask_sensitive_data"
type = "boolean_field"
name = "Mask Sensitive Data"
default = true
